In [100]:
import pandas as pd

#url = 'https://raw.githubusercontent.com/rodgersnick13/PokemonDataPipeline/refs/heads/main/pokemon.csv'
df = pd.read_csv("pokemon.csv")
#df = pd.read_csv(url)
df = pd.DataFrame(df)
df = df.set_index('pokedex_number')
print(df.head(10))
print(df.describe())

                                  abilities  against_bug  against_dark  \
pokedex_number
1               ['Overgrow', 'Chlorophyll']         1.00           1.0
2               ['Overgrow', 'Chlorophyll']         1.00           1.0
3               ['Overgrow', 'Chlorophyll']         1.00           1.0
4                  ['Blaze', 'Solar Power']         0.50           1.0
5                  ['Blaze', 'Solar Power']         0.50           1.0
6                  ['Blaze', 'Solar Power']         0.25           1.0
7                  ['Torrent', 'Rain Dish']         1.00           1.0
8                  ['Torrent', 'Rain Dish']         1.00           1.0
9                  ['Torrent', 'Rain Dish']         1.00           1.0
10              ['Shield Dust', 'Run Away']         1.00           1.0

                against_dragon  against_electric  against_fairy  \
pokedex_number
1                          1.0               0.5            0.5
2                          1.0               0.5            0.5
3                          1.0               0.5            0.5
4                          1.0               1.0            0.5
5                          1.0               1.0            0.5
6                          1.0               2.0            0.5
7                          1.0               2.0            1.0
8                          1.0               2.0            1.0
9                          1.0               2.0            1.0
10                         1.0               1.0            1.0

                against_fight  against_fire  against_flying  against_ghost  \
pokedex_number
1                         0.5           2.0             2.0            1.0
2                         0.5           2.0             2.0            1.0
3                         0.5           2.0             2.0            1.0
4                         1.0           0.5             1.0            1.0
5                         1.0           0.5             1.0            1.0
6                         0.5           0.5             1.0            1.0
7                         1.0           0.5             1.0            1.0
8                         1.0           0.5             1.0            1.0
9                         1.0           0.5             1.0            1.0
10                        0.5           2.0             2.0            1.0

                ...        name  percentage_male  sp_attack  sp_defense  \
pokedex_number  ...
1               ...   Bulbasaur             88.1         65          65
2               ...     Ivysaur             88.1         80          80
3               ...    Venusaur             88.1        122         120
4               ...  Charmander             88.1         60          50
5               ...  Charmeleon             88.1         80          65
6               ...   Charizard             88.1        159         115
7               ...    Squirtle             88.1         50          64
8               ...   Wartortle             88.1         65          80
9               ...   Blastoise             88.1        135         115
10              ...    Caterpie             50.0         20          20

                speed  type1   type2  weight_kg  generation  is_legendary
pokedex_number
1                  45  grass  poison        6.9           1             0
2                  60  grass  poison       13.0           1             0
3                  80  grass  poison      100.0           1             0
4                  65   fire     NaN        8.5           1             0
5                  80   fire     NaN       19.0           1             0
6                 100   fire  flying       90.5           1             0
7                  43  water     NaN        9.0           1             0
8                  58  water     NaN       22.5           1             0
9                  78  water     NaN       85.5           1             0
10                 45    bug     NaN        2.9           1             0

[10 rows x 40 columns]
       against_bug  against_dark  against_dragon  against_electric  \
count   801.000000    801.000000      801.000000        801.000000
mean      0.996255      1.057116        0.968789          1.073970
std       0.597248      0.438142        0.353058          0.654962
min       0.250000      0.250000        0.000000          0.000000
25%       0.500000      1.000000        1.000000          0.500000
50%       1.000000      1.000000        1.000000          1.000000
75%       1.000000      1.000000        1.000000          1.000000
max       4.000000      4.000000        2.000000          4.000000

       against_fairy  against_fight  against_fire  against_flying  \
count     801.000000     801.000000    801.000000      801.000000
mean        1.068976       1.065543      1.135456        1.192884
std         0.522167       0.717251      0.691853        0.604488
min         0.250000       0.000000      0.250000        0.250000
25%         1.000000       0.500000      0.500000        1.000000
50%         1.000000       1.000000      1.000000        1.000000
75%         1.000000       1.000000      2.000000        1.000000
max         4.000000       4.000000      4.000000        4.000000

       against_ghost  against_grass  ...  experience_growth    height_m  \
count     801.000000     801.000000  ...       8.010000e+02  781.000000
mean        0.985019       1.034020  ...       1.054996e+06    1.163892
std         0.558256       0.788896  ...       1.602558e+05    1.080326
min         0.000000       0.250000  ...       6.000000e+05    0.100000
25%         1.000000       0.500000  ...       1.000000e+06    0.600000
50%         1.000000       1.000000  ...       1.000000e+06    1.000000
75%         1.000000       1.000000  ...       1.059860e+06    1.500000
max         4.000000       4.000000  ...       1.640000e+06   14.500000

               hp  percentage_male   sp_attack  sp_defense       speed  \
count  801.000000       703.000000  801.000000  801.000000  801.000000
mean    68.958801        55.155761   71.305868   70.911361   66.334582
std     26.576015        20.261623   32.353826   27.942501   28.907662
min      1.000000         0.000000   10.000000   20.000000    5.000000
25%     50.000000        50.000000   45.000000   50.000000   45.000000
50%     65.000000        50.000000   65.000000   66.000000   65.000000
75%     80.000000        50.000000   91.000000   90.000000   85.000000
max    255.000000       100.000000  194.000000  230.000000  180.000000

        weight_kg  generation  is_legendary
count  781.000000  801.000000    801.000000
mean    61.378105    3.690387      0.087391
std    109.354766    1.930420      0.282583
min      0.100000    1.000000      0.000000
25%      9.000000    2.000000      0.000000
50%     27.300000    4.000000      0.000000
75%     64.800000    5.000000      0.000000
max    999.900000    7.000000      1.000000

[8 rows x 33 columns]

In [101]:
display(df)

,abilities,against_bug,against_dark,against_dragon,against_electric,against_fairy,against_fight,against_fire,against_flying,against_ghost,...,name,percentage_male,sp_attack,sp_defense,speed,type1,type2,weight_kg,generation,is_legendary
pokedex_number,,,,,,,,,,,,,,,,,,,,,
1,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,Bulbasaur,88.1,65,65,45,grass,poison,6.9,1,0
2,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,Ivysaur,88.1,80,80,60,grass,poison,13.0,1,0
3,"['Overgrow', 'Chlorophyll']",1.00,1.0,1.0,0.5,0.5,0.5,2.0,2.0,1.0,...,Venusaur,88.1,122,120,80,grass,poison,100.0,1,0
4,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,Charmander,88.1,60,50,65,fire,NaN,8.5,1,0
5,"['Blaze', 'Solar Power']",0.50,1.0,1.0,1.0,0.5,1.0,0.5,1.0,1.0,...,Charmeleon,88.1,80,65,80,fire,NaN,19.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
797,['Beast Boost'],0.25,1.0,0.5,2.0,0.5,1.0,2.0,0.5,1.0,...,Celesteela,NaN,107,101,61,steel,flying,999.9,7,1
798,['Beast Boost'],1.00,1.0,0.5,0.5,0.5,2.0,4.0,1.0,1.0,...,Kartana,NaN,59,31,109,grass,steel,0.1,7,1
799,['Beast Boost'],2.00,0.5,2.0,0.5,4.0,2.0,0.5,1.0,0.5,...,Guzzlord,NaN,97,53,43,dark,dragon,888.0,7,1
800,['Prism Armor'],2.00,2.0,1.0,1.0,1.0,0.5,1.0,1.0,2.0,...,Necrozma,NaN,127,89,79,psychic,NaN,230.0,7,1
801,['Soul-Heart'],0.25,0.5,0.0,1.0,0.5,1.0,2.0,0.5,1.0,...,Magearna,NaN,130,115,65,steel,fairy,80.5,7,1

Dropping unneeded columns

In [102]:
df = df.drop(['against_bug', 'against_bug', 'against_dark', 'against_dragon',
                           'against_electric', 'against_fairy', 'against_fight', 'against_fire',
                           'against_flying', 'against_ghost', 'against_grass', 'against_ground',
                           'against_ice', 'against_normal', 'against_poison', 'against_psychic',
                           'against_rock', 'against_steel', 'against_water', 'japanese_name',
                           'generation', 'classfication', 'base_egg_steps', 'abilities',
                           'base_total', 'sp_attack', 'sp_defense', 'type2', 'percentage_male',
                           'experience_growth'], axis=1)

In [ ]:
df = df.dropna(subset=['height_m'])
df['is_legendary'] = df['is_legendary'].astype(bool)

df = df[df['capture_rate'] != '30 (Meteorite)255 (Core)']
df['capture_rate'] = df['capture_rate'].astype(int)

In [119]:
display(df)
df.describe()
#df.count()

,attack,base_happiness,capture_rate,defense,height_m,hp,name,speed,type1,weight_kg,is_legendary
pokedex_number,,,,,,,,,,,
1,49,70,45,49,0.7,45,Bulbasaur,45,grass,6.9,False
2,62,70,45,63,1.0,60,Ivysaur,60,grass,13.0,False
3,100,70,45,123,2.0,80,Venusaur,80,grass,100.0,False
4,52,70,45,43,0.6,39,Charmander,65,fire,8.5,False
5,64,70,45,58,1.1,58,Charmeleon,80,fire,19.0,False
...,...,...,...,...,...,...,...,...,...,...,...
797,101,0,25,103,9.2,97,Celesteela,61,steel,999.9,True
798,181,0,255,131,0.3,59,Kartana,109,grass,0.1,True
799,101,0,15,53,5.5,223,Guzzlord,43,dark,888.0,True
800,107,0,3,101,2.4,97,Necrozma,79,psychic,230.0,True
801,95,0,3,115,1.0,80,Magearna,65,steel,80.5,True

,attack,base_happiness,capture_rate,defense,height_m,hp,speed,weight_kg
count,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000,780.000000
mean,77.665385,65.198718,97.941026,73.019231,1.165000,69.160256,66.210256,61.405513
std,32.234492,19.807942,75.886691,30.822251,1.080576,26.636742,28.858548,109.422248
min,5.000000,0.000000,3.000000,5.000000,0.100000,1.000000,5.000000,0.100000
25%,55.000000,70.000000,45.000000,50.000000,0.600000,50.000000,45.000000,9.000000
50%,75.000000,70.000000,60.000000,70.000000,1.000000,65.000000,64.500000,27.150000
75%,100.000000,70.000000,156.250000,90.000000,1.500000,80.000000,85.000000,64.850000
max,185.000000,140.000000,255.000000,230.000000,14.500000,255.000000,180.000000,999.900000